### ISSUE TITLE
Need somewhere to securly store passwords (Outside of Source)

### ISSUE THREAD

**Issue by GrantBaum** [GrantBaum/MyMICDS-Admin-Pannel#1]
When an admin logs in we dont want the password to be taken from a json file (unless we encrypt it, which is an option) we need them to log in with the username and password and that will be associated with a UUID in the UserWhitelist.json file. Where do we store the passwords, or how do we encrypt/decrypt them?

**Comment by michaelgira23** [comment]
Ideally, we hook this up to the existing MyMICDS backend and use the same exact authentication mechanism for this admin panel. Any backend actions we need for this app can be added with the existing backend.

**Comment by GrantBaum** [comment]
so all we need to do is the UI and frontend? and we can use the same api? we will still need some backend code here tho right?

**Comment by michaelgira23** [comment]
Yes! And we've separated the frontend code for calling the MyMICDS backend API, so you should be able to reuse and add onto it
https://github.com/MyMICDS/MyMICDS-SDK

This will hopefully make your life a whole lot easier because you can use our existing infrastructure and structure any new potential API calls in a similar way.

**Comment by GrantBaum** [comment]
so then right now i can just stick all that code into the existing API folder in this repository? and we can modify it for a working API?

**Comment by michaelgira23** [comment]
Best practice would be to download the MyMICDS SDK from the npm registry, so invoking `npm install @mymicds/sdk`. If you ever need to add a new feature, you can create a PR to the MyMICDS-SDK repo directly and publish a newer version on npm.

**Comment by GrantBaum** [comment]
using API
